# Site settings
encoding: "utf-8"
title: Magento2中文开发文档
email: mailto:DL-Magento-Doc-Feedback@ebay.com
description: Magento2中文开发手册
baseurl: "/"
# url: "https://github.com/magento/devdocs" # the base hostname & protocol for your site
# twitter_username: magento
# github_username:  magento

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

gdeurl: "/guides/v2.0/"
githuburl: "https://github.com/magento/devdocs/tree/develop/guides/v2.0/"
namem2fedg: "Magento2前端开发手册"
namem2devgde: "Magento2开发手册"
namem2apiref: "Magento2 API文档"
namem2install: "Magento2安装手册"
mage2000url: "https://github.com/magento/magento2/blob/develop/"
# toc_baseurl: "https://github.corp.ebay.com/pages/Magento/devdocs_internal"
m1xgdeurl: "/guides/m1x/"
m1xgithuburl: "https://github.com/magento/devdocs/tree/develop/guides/m1x/"

# Build settings
markdown: kramdown
highlighter: pygments

incremental: true

gems:
  - jekyll-redirect-from

exclude: ['scss','bin','node_modules']
